_target_: tspfn.architecture.prediction_heads.PFNPredictionHead
in_features: ${task.embed_dim}
model_path: ${task.model.encoder.tabpfn_kwargs.model_path}
updated_pfn_path: ${task.model.encoder.updated_pfn_path}