_target_: tspfn.architecture.prediction_heads.PFNPredictionHead
in_features: ${task.embed_dim}
tabpfn_kwargs: ${task.model.encoder.tabpfn_kwargs}
updated_pfn_path: ${task.model.encoder.updated_pfn_path}
num_classes: ${data.num_classes}