_target_: tspfn.architecture.patchTST.patchTST.PatchTST
c_in: ${data.num_channels}
seq_len: ${data.time_series_length}
target_dim: ${data.num_classes}
patch_len: ${task.patch_len}
stride: ${task.stride}
mean_pool: False
d_model: 128